logging:
  format: "[%(levelname)s]-%(lineno)s: %(message)s]"
  level: INFO
  name: Mr.Logger
  streamHandler: ext://sys.stdout


project:
  path: '/Users/aymankhechman/Desktop/ml_expert/ML Pipeline'
  pipeline_folder: ${base.project.path}/pipelines
  pipeline_name: pipeline_v2_rf.pkl

