stages:
  download_dataset: 
    cmd: python stages/download_data.py
    deps:
      - config/dataset/dataset_2024.yaml
      - config/config.yaml
    outs:
      - dataset/2024/yellow_tripdata_2024_new_t.parquet
  run_pipeline:
    cmd: python stages/main.py
    deps:
      - config/modelling
      - stages/pipeline.py
    outs:
      - pipelines/pipeline_v2_rf.pkl