defaults:
  - feature-selection:
    - DropFeatures
  - feature-engineering:
    - DatetimeSubtraction
  - imputer:
    - CategoricalImputer
    - MeanMedianImputer
  - encoding:
    - DatetimeFeatures
    - OneHotEncoder
  - models:
    - HistGradientBoostingRegressor